In [ ]:
import pandas as pd
import numpy as np


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
mydata = pd.read_csv('/content/gdrive/My Drive/sample_data/student-perfor.csv')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


FileNotFoundError: ignored

In [ ]:
df['Division'].unique()

In [ ]:
df['Division'] = df['Division'].replace({'A':0, 'B':1})

In [ ]:
df['Division'].unique()

array([1, 0], dtype=int64)

# AGE COLUMN PREPROCESSING

In [ ]:
df['Age'].unique()

array([20, 21, 19, 22], dtype=int64)

In [ ]:
df['Age'].isnull().sum()

0

In [ ]:
#normalization

# Gender Column Preprocessing

In [ ]:
df['Gender '].unique()

array(['F', 'M'], dtype=object)

In [ ]:
df['Gender '] = df['Gender '].replace({'M':0, 'F':1})

In [ ]:
df['Gender '].unique()

array([1, 0], dtype=int64)

In [ ]:
df.head()

Timestamp                        Email Address  \
0  1/18/2022 14:34:30      nikita.khairnar19@pccoepune.org   
1  1/18/2022 14:34:31    krishnankit.dixit19@pccoepune.org   
2  1/18/2022 14:34:38  karthi.dhanasekaran19@pccoepune.org   
3  1/18/2022 14:34:44       shreyash.patil19@pccoepune.org   
4  1/18/2022 14:34:54       hitesh.kotecha19@pccoepune.org   

         Name of student Roll Number (e.g. A101, B202)  Division  Age  \
0  Nikita Vijay Khairnar                           213         1   20   
1      Krishnankit Dixit                           143         0   21   
2    Karthi Dhanasekaran                           275         1   21   
3         Shreyash patil                           264         1   21   
4         Hitesh Kotecha                           220         1   20   

   Gender  Study time in hrs  FE pointer(e.g. 7.9)  SE pointer(e.g. 7.9)  \
0        1                 3                  9.20                  9.95   
1        0                 5                  9.36                  9.41   
2        0                 2                  8.45                  9.45   
3        0               0.7                  8.50                  9.20   
4        0                 4                  8.40                  8.70   

  number of subject failed in current backlogs  \
0                           0                0   
1                           0                0   
2                           0                0   
3                           0                0   
4                           0                0   

                            Additional courses opted  \
0                                                NaN   
1  Web development, Python, Data structures and a...   
2                                              AI/ML   
3                                     Python, c, c++   
4                                                  0   

  number of paper published  intership opted 10th marks in percentage  \
0                       NaN              YES                     93.6   
1                         0              YES                       89   
2                         1              YES                     82.8   
3                         1               NO                       89   
4                         0              YES                       88   

  12th marks in percentage 10th and 12th university/board  
0                    82.31                          STATE  
1                       83                          STATE  
2                     84.6                           CBSE  
3                       79                          STATE  
4                       74                          STATE

# FE Pointer Column Preprocessing

In [ ]:
type(df['FE pointer(e.g. 7.9)'][0])

numpy.float64

In [ ]:
df['FE pointer(e.g. 7.9)'].isnull().sum()

10

In [ ]:
avg_fe_pointer = df['FE pointer(e.g. 7.9)'].sum()

In [ ]:
avg_fe_pointer/=122

In [ ]:
avg_fe_pointer

7.460245901639344

In [ ]:
type(df['FE pointer(e.g. 7.9)'].isnull())

pandas.core.series.Series

In [ ]:
for i in df['FE pointer(e.g. 7.9)'].isnull().iteritems():
    if(i[1]):
        df['FE pointer(e.g. 7.9)'][i[0]] = avg_fe_pointer

<ipython-input-26-08d102aeaa9d>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FE pointer(e.g. 7.9)'][i[0]] = avg_fe_pointer


In [ ]:
df['FE pointer(e.g. 7.9)'].isnull().sum()

0

# number of subject failed in column preprocessing

In [ ]:
df['number of subject failed in'].isnull().sum()

3

In [ ]:
type(df['number of subject failed in'][0])

str

In [ ]:
df['number of subject failed in'].value_counts()

0       109
1         3
None      2
-         1
3         1
7         1
Na        1
5         1
Name: number of subject failed in, dtype: int64

In [ ]:
df['number of subject failed in'].replace({'None':np.nan,'-':np.nan,'Na':np.nan}, inplace=True)

In [ ]:
df['number of subject failed in'].replace({np.nan:'0'}, inplace=True)

In [ ]:
df['number of subject failed in'].value_counts()

0    116
1      3
3      1
7      1
5      1
Name: number of subject failed in, dtype: int64

# Current Backlogs Column Preprocessing

In [ ]:
df['current backlogs'].value_counts()

0       113
None      3
-         1
Na        1
Name: current backlogs, dtype: int64

In [ ]:
df['current backlogs'].replace({'None':'0','-':'0','Na':'0'}, inplace=True)

In [ ]:
df['current backlogs'].value_counts()

0    118
Name: current backlogs, dtype: int64

In [ ]:
df['current backlogs'].isnull().sum()

4

In [ ]:
df['current backlogs'].replace({np.nan:'0'}, inplace=True)

In [ ]:
df['current backlogs'].isnull().sum()

0

In [ ]:
df.isnull().sum()

Timestamp                          0
Email Address                      0
Name of student                    0
Roll Number (e.g. A101, B202)      0
Division                           0
Age                                0
Gender                             0
Study time in hrs                  6
FE pointer(e.g. 7.9)               0
SE pointer(e.g. 7.9)               0
number of subject failed in        0
current backlogs                   0
Additional courses opted          11
number of paper published          9
 intership opted                   1
10th marks in percentage           0
12th marks in percentage           2
10th and 12th university/board     0
dtype: int64

# number of paper published column preprocessing

In [ ]:
df['number of paper published'].value_counts()

1          56
0          46
2           7
no          1
One         1
-           1
not yet     1
Name: number of paper published, dtype: int64

In [ ]:
df['number of paper published'].replace({'One':'1','-':'0','no':'0', 'not yet':'0'}, inplace=True)

In [ ]:
df['number of paper published'].value_counts()

1    57
0    49
2     7
Name: number of paper published, dtype: int64

In [ ]:
mean_no_of_papers_published = ((1*57) + (0*49) + (2*7))/(57+49+7)

In [ ]:
mean_no_of_papers_published

0.6283185840707964

In [ ]:
for i in df['number of paper published'].isnull().iteritems():
    if(i[1]):
        df['number of paper published'][i[0]] = str(mean_no_of_papers_published)

<ipython-input-46-14da22052cae>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['number of paper published'][i[0]] = str(mean_no_of_papers_published)


In [ ]:
df['number of paper published'].isnull().sum()

0

In [ ]:
df.head()

Timestamp                        Email Address  \
0  1/18/2022 14:34:30      nikita.khairnar19@pccoepune.org   
1  1/18/2022 14:34:31    krishnankit.dixit19@pccoepune.org   
2  1/18/2022 14:34:38  karthi.dhanasekaran19@pccoepune.org   
3  1/18/2022 14:34:44       shreyash.patil19@pccoepune.org   
4  1/18/2022 14:34:54       hitesh.kotecha19@pccoepune.org   

         Name of student Roll Number (e.g. A101, B202)  Division  Age  \
0  Nikita Vijay Khairnar                           213         1   20   
1      Krishnankit Dixit                           143         0   21   
2    Karthi Dhanasekaran                           275         1   21   
3         Shreyash patil                           264         1   21   
4         Hitesh Kotecha                           220         1   20   

   Gender  Study time in hrs  FE pointer(e.g. 7.9)  SE pointer(e.g. 7.9)  \
0        1                 3                  9.20                  9.95   
1        0                 5                  9.36                  9.41   
2        0                 2                  8.45                  9.45   
3        0               0.7                  8.50                  9.20   
4        0                 4                  8.40                  8.70   

  number of subject failed in current backlogs  \
0                           0                0   
1                           0                0   
2                           0                0   
3                           0                0   
4                           0                0   

                            Additional courses opted  \
0                                                NaN   
1  Web development, Python, Data structures and a...   
2                                              AI/ML   
3                                     Python, c, c++   
4                                                  0   

  number of paper published  intership opted 10th marks in percentage  \
0        0.6283185840707964              YES                     93.6   
1                         0              YES                       89   
2                         1              YES                     82.8   
3                         1               NO                       89   
4                         0              YES                       88   

  12th marks in percentage 10th and 12th university/board  
0                    82.31                          STATE  
1                       83                          STATE  
2                     84.6                           CBSE  
3                       79                          STATE  
4                       74                          STATE

In [ ]:
df.isnull().sum()

Timestamp                          0
Email Address                      0
Name of student                    0
Roll Number (e.g. A101, B202)      0
Division                           0
Age                                0
Gender                             0
Study time in hrs                  6
FE pointer(e.g. 7.9)               0
SE pointer(e.g. 7.9)               0
number of subject failed in        0
current backlogs                   0
Additional courses opted          11
number of paper published          0
 intership opted                   1
10th marks in percentage           0
12th marks in percentage           2
10th and 12th university/board     0
dtype: int64